Feat/Restart after finish
yshima42/shirafu_life pull request #136
Opened 2023-06-01 10:40 UTC by hyoshie

Close #130 
### やったこと
- 習慣未設定時、前回の習慣を登録できるボタンを追加

### 気になったこと
- Congratulationページにボタンを作る予定でしたが、やめました。
ホーム画面に戻ったら見れるし、ボタンの名前がうまく決まらなかったので。
- ホーム画面にオレンジのボタン二つは少し主張が強いので、色を変えた方がいい気がします。

### 次やること
- refactor: HabitクラスとDBのHabitテーブルの名前を変更する。
DBのテーブルを移行できるように

2023-06-01 14:47 UTC, yshima42 requested changes
設計が悪くて申し訳ない。近いうちに修正しないととんでもないことになりますね。

2023-06-01 14:47 UTC, yshima42 commented on lib/screens/home_page.dart
> +        widget.habitProvider.insertHabit(latestHabit.createCopyWithNewStart());
スタートエントリーとアチーブメントエントリーが入っていない

設計が悪くて大変申し訳無いのですが、registration_page.dartの176行目のcreateAchievementEntriesを入れてもらえるとスタートエントリーと、Achievementが入ります。
```
  Future<void> _createAchievementEntries() async {
    final notificationProvider = NotificationProvider();
    final startDate = registrationState.startDate;
    var habitName = registrationState.habitName;

    if (habitName.length > kHabitNameMaxDisplayLength) {
      habitName = '${habitName.substring(0, kHabitNameMaxDisplayLength)}...';
    }

    for (var i = 0; i < kGoalDaysRanges.length; i++) {
      final date = startDate.add(Duration(days: kGoalDaysRanges[i]));
      final achievementDiary = Diary(
        entry: '$habitName ${kGoalDaysRanges[i]}日達成！',
        createdAt: date,
        status: DiaryStatus.goalAchieved,
      );
      await notificationProvider.insertNotification(achievementDiary);
    }

    final startNotification = Diary(
      entry: '$habitName スタート',
      createdAt: startDate,
      status: DiaryStatus.start,
    );
    await notificationProvider.insertNotification(startNotification);
  }
```

2023-06-01 16:04 UTC, hyoshie commented on lib/screens/home_page.dart
> +        widget.habitProvider.insertHabit(latestHabit.createCopyWithNewStart());
関数を作りました。
providerのDIするか統一できてませんが、メリットの方が大きいと思ったので。

2023-06-02 00:20 UTC, yshima42 approved these changes
リファクターしてくれてありがとうございます。

2023-06-02 00:21 UTC, merged